// src/contexts/AuthContext.js
import { createContext, useContext, useState, useEffect } from "react";
import { CognitoUserPool } from "amazon-cognito-identity-js";
import awsExports from "../aws-exports"; // generated by Amplify CLI

// Configure your pool from aws-exports
const poolData = {
  UserPoolId: awsExports.aws_user_pools_id,
  ClientId: awsExports.aws_user_pools_web_client_id,
};
const userPool = new CognitoUserPool(poolData);

const AuthContext = createContext();

export const AuthProvider = ({ children }) => {
  const [cognitoId, setCognitoId] = useState(null);
  const [userProfile, setUserProfile] = useState(null);
  const [loading, setLoading] = useState(true);

  // On mount, grab current user & load attributes
  useEffect(() => {
    const user = userPool.getCurrentUser();
    if (!user) {
      console.warn("No Cognito user found");
      setLoading(false);
      return;
    }
    setCognitoId(user.getUsername());
    // you must have a valid session for getUserAttributes to work
    user.getSession((errSession, session) => {
      if (errSession) {
        console.error("Error getting session:", errSession);
        setLoading(false);
        return;
      }
      user.getUserAttributes((err, attrs) => {
        if (err) {
          console.error("Error fetching user attributes:", err);
          setLoading(false);
          return;
        }
        // convert array to object
        const profile = attrs.reduce((acc, a) => {
          acc[a.getName()] = a.getValue();
          return acc;
        }, {});
        setUserProfile(profile);
        setLoading(false);
      });
    });
  }, []);

  // updateProfile: calls CognitoUser.updateAttributes
  const updateProfile = (updates) =>
    new Promise((resolve, reject) => {
      const user = userPool.getCurrentUser();
      if (!user) return reject(new Error("No user"));
      // ensure session
      user.getSession((e1, session) => {
        if (e1) return reject(e1);
        // build CognitoUserAttribute list
        const attributeList = Object.entries(updates).map(
          ([Name, Value]) =>
            new window.AmazonCognitoIdentity.CognitoUserAttribute({ Name, Value })
        );
        user.updateAttributes(attributeList, (err, result) => {
          if (err) return reject(err);
          // merge locally
          setUserProfile((p) => ({ ...p, ...updates }));
          resolve(result);
        });
      });
    });

  return (
    <AuthContext.Provider
      value={{ cognitoId, userProfile, updateProfile, loading }}
    >
      {children}
    </AuthContext.Provider>
  );
};

export const useAuth = () => useContext(AuthContext);
