service: my-service

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1

  httpApi:
    cors:
      allowedOrigins:
        - https://master.d2fdrxobxyr2je.amplifyapp.com
        - http://localhost:3000
      allowedHeaders:
        - Content-Type
        - Authorization
        - X-Requested-With
        - Origin
        - Accept
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowCredentials: true

functions:
  app:
    handler: index.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: '*'

plugins:
  - serverless-offline
