service: my-service

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  stage: dev
  logs:
    restApi: true
  tracing:
    apiGateway: true
  apiGateway:
    shouldStartNameWithService: true
    minimumCompressionSize: 1024
    binaryMediaTypes:
      - '*/*'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: health
          method: GET
          cors: true
      - http:
          path: api/goods-in
          method: GET
          cors:
            origin: "'https://master.d2fdrxobxyr2je.amplifyapp.com'"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: true
            maxAge: 86400
      - http:
          path: api/submit
          method: POST
          cors:
            origin: "'https://master.d2fdrxobxyr2je.amplifyapp.com'"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: true
            maxAge: 86400
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: "'https://master.d2fdrxobxyr2je.amplifyapp.com'"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: true
            maxAge: 86400

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true
