service: my-service

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  stage: dev

  apiGateway:
    shouldStartNameWithService: true
    minimumCompressionSize: 1024

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  - serverless-offline
